// 自動產生的 icon 路徑對應表
// Wildmap — 台灣戶外活動地圖平台
// 產生時間：2026-03-06

export const FEATURE_ICONS: Record<string, string> = {
  // === 分類 icon（6 個）===
  camping: '/icons/camping.svg',
  carcamp: '/icons/carcamp.svg',
  fishing: '/icons/fishing.svg',
  diving: '/icons/diving.svg',
  surfing: '/icons/surfing.svg',
  hiking: '/icons/hiking.svg',

  // === 營地特性 camp_traits（21 個）===
  tent_site: '/icons/tent_site.svg',
  car_beside_tent: '/icons/car_beside_tent.svg',
  rv_site: '/icons/rv_site.svg',
  glamping: '/icons/glamping.svg',
  cabin: '/icons/cabin.svg',
  covered_area: '/icons/covered_area.svg',
  small_group_area: '/icons/small_group_area.svg',
  grassland: '/icons/grassland.svg',
  gravel_site: '/icons/gravel_site.svg',
  flat_ground: '/icons/flat_ground.svg',
  shaded: '/icons/shaded.svg',
  night_view: '/icons/night_view.svg',
  sunrise_view: '/icons/sunrise_view.svg',
  sea_of_clouds: '/icons/sea_of_clouds.svg',
  stargazing: '/icons/stargazing.svg',
  seasonal_flowers: '/icons/seasonal_flowers.svg',
  fireflies: '/icons/fireflies.svg',
  pet_friendly: '/icons/pet_friendly.svg',
  family_friendly: '/icons/family_friendly.svg',
  beginner_friendly: '/icons/beginner_friendly.svg',
  quiet_zone: '/icons/quiet_zone.svg',

  // === 設施與服務 facilities（22 個）===
  flush_toilet: '/icons/flush_toilet.svg',
  squat_toilet: '/icons/squat_toilet.svg',
  shower: '/icons/shower.svg',
  hot_water: '/icons/hot_water.svg',
  sink: '/icons/sink.svg',
  shared_kitchen: '/icons/shared_kitchen.svg',
  electricity: '/icons/electricity.svg',
  wifi: '/icons/wifi.svg',
  '4g_5g': '/icons/4g_5g.svg',
  drinking_water: '/icons/drinking_water.svg',
  trash_disposal: '/icons/trash_disposal.svg',
  fire_pit: '/icons/fire_pit.svg',
  bbq_area: '/icons/bbq_area.svg',
  playground: '/icons/playground.svg',
  swimming_pool: '/icons/swimming_pool.svg',
  equipment_rental: '/icons/equipment_rental.svg',
  food_service: '/icons/food_service.svg',
  convenience_store: '/icons/convenience_store.svg',
  gas_station: '/icons/gas_station.svg',
  managed: '/icons/managed.svg',
  reservation_required: '/icons/reservation_required.svg',
  free_camping: '/icons/free_camping.svg',

  // === 周邊環境 environment（20 個）===
  river_stream: '/icons/river_stream.svg',
  lake: '/icons/lake.svg',
  ocean_view: '/icons/ocean_view.svg',
  beach: '/icons/beach.svg',
  mountain_view: '/icons/mountain_view.svg',
  forest: '/icons/forest.svg',
  hot_spring: '/icons/hot_spring.svg',
  wild_hot_spring: '/icons/wild_hot_spring.svg',
  waterfall: '/icons/waterfall.svg',
  farm_experience: '/icons/farm_experience.svg',
  aboriginal_culture: '/icons/aboriginal_culture.svg',
  temple_nearby: '/icons/temple_nearby.svg',
  scenic_trail: '/icons/scenic_trail.svg',
  cycling_path: '/icons/cycling_path.svg',
  bird_watching: '/icons/bird_watching.svg',
  wildlife: '/icons/wildlife.svg',
  botanical: '/icons/botanical.svg',
  rock_formation: '/icons/rock_formation.svg',
  historical_site: '/icons/historical_site.svg',
  panoramic_view: '/icons/panoramic_view.svg',

  // === 可進行活動 activities（18 個）===
  hiking_activity: '/icons/hiking_activity.svg',
  fishing_activity: '/icons/fishing_activity.svg',
  swimming: '/icons/swimming.svg',
  kayaking: '/icons/kayaking.svg',
  cycling: '/icons/cycling.svg',
  rock_climbing: '/icons/rock_climbing.svg',
  paragliding: '/icons/paragliding.svg',
  photography: '/icons/photography.svg',
  meditation: '/icons/meditation.svg',
  yoga: '/icons/yoga.svg',
  astronomy: '/icons/astronomy.svg',
  foraging: '/icons/foraging.svg',
  cooking_outdoor: '/icons/cooking_outdoor.svg',
  campfire: '/icons/campfire.svg',
  night_hiking: '/icons/night_hiking.svg',
  grass_sledding: '/icons/grass_sledding.svg',
  farm_picking: '/icons/farm_picking.svg',
  diy_craft: '/icons/diy_craft.svg',

  // === 區域與限制 restrictions（14 個）===
  no_pets: '/icons/no_pets.svg',
  no_smoking: '/icons/no_smoking.svg',
  no_alcohol: '/icons/no_alcohol.svg',
  no_campfire: '/icons/no_campfire.svg',
  no_music: '/icons/no_music.svg',
  quiet_hours: '/icons/quiet_hours.svg',
  check_in_time: '/icons/check_in_time.svg',
  check_out_time: '/icons/check_out_time.svg',
  max_capacity: '/icons/max_capacity.svg',
  age_restriction: '/icons/age_restriction.svg',
  vehicle_restriction: '/icons/vehicle_restriction.svg',
  seasonal_open: '/icons/seasonal_open.svg',
  permit_required: '/icons/permit_required.svg',
  indigenous_land: '/icons/indigenous_land.svg',

  // === 注意事項 warnings（11 個）===
  steep_terrain: '/icons/steep_terrain.svg',
  flood_risk: '/icons/flood_risk.svg',
  landslide_risk: '/icons/landslide_risk.svg',
  insect_warning: '/icons/insect_warning.svg',
  snake_warning: '/icons/snake_warning.svg',
  boar_warning: '/icons/boar_warning.svg',
  leech_warning: '/icons/leech_warning.svg',
  no_cell_signal: '/icons/no_cell_signal.svg',
  road_condition: '/icons/road_condition.svg',
  limited_parking: '/icons/limited_parking.svg',
  bear_warning: '/icons/bear_warning.svg',

  // === 導航/UI icon（10 個）===
  navigate: '/icons/navigate.svg',
  favorite: '/icons/favorite.svg',
  share: '/icons/share.svg',
  edit: '/icons/edit.svg',
  report: '/icons/report.svg',
  verified: '/icons/verified.svg',
  photo: '/icons/photo.svg',
  comment: '/icons/comment.svg',
  star: '/icons/star.svg',
  filter: '/icons/filter.svg',
}

// 分類群組對應
export const ICON_CATEGORIES = {
  categories: ['camping', 'carcamp', 'fishing', 'diving', 'surfing', 'hiking'],
  camp_traits: [
    'tent_site', 'car_beside_tent', 'rv_site', 'glamping', 'cabin',
    'covered_area', 'small_group_area', 'grassland', 'gravel_site',
    'flat_ground', 'shaded', 'night_view', 'sunrise_view', 'sea_of_clouds',
    'stargazing', 'seasonal_flowers', 'fireflies', 'pet_friendly',
    'family_friendly', 'beginner_friendly', 'quiet_zone',
  ],
  facilities: [
    'flush_toilet', 'squat_toilet', 'shower', 'hot_water', 'sink',
    'shared_kitchen', 'electricity', 'wifi', '4g_5g', 'drinking_water',
    'trash_disposal', 'fire_pit', 'bbq_area', 'playground', 'swimming_pool',
    'equipment_rental', 'food_service', 'convenience_store', 'gas_station',
    'managed', 'reservation_required', 'free_camping',
  ],
  environment: [
    'river_stream', 'lake', 'ocean_view', 'beach', 'mountain_view',
    'forest', 'hot_spring', 'wild_hot_spring', 'waterfall', 'farm_experience',
    'aboriginal_culture', 'temple_nearby', 'scenic_trail', 'cycling_path',
    'bird_watching', 'wildlife', 'botanical', 'rock_formation',
    'historical_site', 'panoramic_view',
  ],
  activities: [
    'hiking_activity', 'fishing_activity', 'swimming', 'kayaking', 'cycling',
    'rock_climbing', 'paragliding', 'photography', 'meditation', 'yoga',
    'astronomy', 'foraging', 'cooking_outdoor', 'campfire', 'night_hiking',
    'grass_sledding', 'farm_picking', 'diy_craft',
  ],
  restrictions: [
    'no_pets', 'no_smoking', 'no_alcohol', 'no_campfire', 'no_music',
    'quiet_hours', 'check_in_time', 'check_out_time', 'max_capacity',
    'age_restriction', 'vehicle_restriction', 'seasonal_open',
    'permit_required', 'indigenous_land',
  ],
  warnings: [
    'steep_terrain', 'flood_risk', 'landslide_risk', 'insect_warning',
    'snake_warning', 'boar_warning', 'leech_warning', 'no_cell_signal',
    'road_condition', 'limited_parking', 'bear_warning',
  ],
  ui: [
    'navigate', 'favorite', 'share', 'edit', 'report',
    'verified', 'photo', 'comment', 'star', 'filter',
  ],
} as const

// 中文名稱對應
export const ICON_LABELS: Record<string, string> = {
  // 分類
  camping: '露營',
  carcamp: '車宿',
  fishing: '釣魚',
  diving: '潛水',
  surfing: '衝浪',
  hiking: '登山',
  // 營地特性
  tent_site: '帳篷營位',
  car_beside_tent: '車停帳邊',
  rv_site: '露營車營位',
  glamping: '豪華帳篷',
  cabin: '小木屋',
  covered_area: '雨棚',
  small_group_area: '小包區',
  grassland: '大草皮',
  gravel_site: '碎石地',
  flat_ground: '平坦地面',
  shaded: '有遮蔭',
  night_view: '夜景',
  sunrise_view: '日出',
  sea_of_clouds: '雲海',
  stargazing: '觀星',
  seasonal_flowers: '季節花卉',
  fireflies: '螢火蟲',
  pet_friendly: '寵物友善',
  family_friendly: '親子友善',
  beginner_friendly: '新手友善',
  quiet_zone: '安靜區',
  // 設施與服務
  flush_toilet: '沖水廁所',
  squat_toilet: '蹲式廁所',
  shower: '淋浴',
  hot_water: '熱水',
  sink: '洗滌槽',
  shared_kitchen: '公用廚房',
  electricity: '電力供應',
  wifi: 'WiFi',
  '4g_5g': '手機訊號',
  drinking_water: '飲用水',
  trash_disposal: '垃圾處理',
  fire_pit: '營火區',
  bbq_area: '烤肉區',
  playground: '遊樂設施',
  swimming_pool: '戲水池',
  equipment_rental: '租借裝備',
  food_service: '餐飲服務',
  convenience_store: '便利商店',
  gas_station: '加油站',
  managed: '有管理員',
  reservation_required: '需預約',
  free_camping: '免費',
  // 周邊環境
  river_stream: '溪流',
  lake: '湖泊',
  ocean_view: '海景',
  beach: '沙灘',
  mountain_view: '山景',
  forest: '森林',
  hot_spring: '溫泉',
  wild_hot_spring: '野溪溫泉',
  waterfall: '瀑布',
  farm_experience: '農場體驗',
  aboriginal_culture: '原住民文化',
  temple_nearby: '寺廟附近',
  scenic_trail: '步道',
  cycling_path: '自行車道',
  bird_watching: '賞鳥',
  wildlife: '野生動物',
  botanical: '植物生態',
  rock_formation: '特殊地質',
  historical_site: '歷史古蹟',
  panoramic_view: '全景視野',
  // 可進行活動
  hiking_activity: '登山健行',
  fishing_activity: '釣魚',
  swimming: '游泳/玩水',
  kayaking: '划船/獨木舟',
  cycling: '自行車',
  rock_climbing: '攀岩',
  paragliding: '飛行傘',
  photography: '攝影',
  meditation: '冥想/靜心',
  yoga: '瑜珈',
  astronomy: '天文觀測',
  foraging: '採集',
  cooking_outdoor: '戶外烹飪',
  campfire: '營火活動',
  night_hiking: '夜間健行',
  grass_sledding: '滑草',
  farm_picking: '採果',
  diy_craft: 'DIY 手作',
  // 區域與限制
  no_pets: '禁止寵物',
  no_smoking: '禁止吸菸',
  no_alcohol: '禁止飲酒',
  no_campfire: '禁止營火',
  no_music: '禁止喧嘩',
  quiet_hours: '安靜時段',
  check_in_time: '入場時間',
  check_out_time: '退場時間',
  max_capacity: '人數上限',
  age_restriction: '年齡限制',
  vehicle_restriction: '車輛限制',
  seasonal_open: '季節性開放',
  permit_required: '需要許可證',
  indigenous_land: '原住民保留地',
  // 注意事項
  steep_terrain: '地形陡峭',
  flood_risk: '水災風險',
  landslide_risk: '落石風險',
  insect_warning: '蚊蟲多',
  snake_warning: '蛇類出沒',
  boar_warning: '山豬出沒',
  leech_warning: '螞蝗',
  no_cell_signal: '無手機訊號',
  road_condition: '路況差',
  limited_parking: '停車位少',
  bear_warning: '熊出沒',
  // 導航/UI
  navigate: '導航',
  favorite: '收藏',
  share: '分享',
  edit: '編輯',
  report: '檢舉',
  verified: '已驗證',
  photo: '照片',
  comment: '評論',
  star: '星星評分',
  filter: '篩選',
}
