-- 014: 新增聯絡欄位 + gov_certified 欄位
-- 用於儲存露營場聯絡資訊和政府認證狀態

ALTER TABLE spots ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS facebook TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS instagram TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS line_id TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS google_maps_url TEXT;
ALTER TABLE spots ADD COLUMN IF NOT EXISTS gov_certified BOOLEAN DEFAULT false;
